"""initial schema

Revision ID: 779186aebb61
Revises: 
Create Date: 2026-08-06 17:42:40.036663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '779186aebb61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_run_id', sa.String(length=36), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_waiting_hours', sa.Float(), nullable=False),
    sa.Column('makespan_hours', sa.Float(), nullable=False),
    sa.Column('solver_status', sa.String(length=20), nullable=False),
    sa.Column('solve_time_seconds', sa.Float(), nullable=False),
    sa.Column('assignments', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('layout_name', sa.String(length=80), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('sim_duration_hours', sa.Float(), nullable=False),
    sa.Column('sim_clock_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('max_draft_m', sa.Float(), nullable=False),
    sa.Column('crane_slots', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('empty', 'occupied', 'maintenance', name='berthstatus'), nullable=False),
    sa.Column('current_ship_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('container_no', sa.String(length=20), nullable=False),
    sa.Column('ship_id', sa.String(length=36), nullable=True),
    sa.Column('yard_block_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('on_vessel', 'in_yard', 'on_truck', 'gate_out', name='containerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cranes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('berth_code', sa.String(length=20), nullable=True),
    sa.Column('moves_per_hour', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'active', 'maintenance', name='cranestatus'), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sim_time_hours', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'congested', name='gatestatus'), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sim_ref', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=False),
    sa.Column('size_teu', sa.Integer(), nullable=False),
    sa.Column('containers_to_discharge', sa.Integer(), nullable=False),
    sa.Column('containers_to_load', sa.Integer(), nullable=False),
    sa.Column('eta_hours', sa.Float(), nullable=False),
    sa.Column('ata_hours', sa.Float(), nullable=True),
    sa.Column('berthed_hours', sa.Float(), nullable=True),
    sa.Column('etd_hours', sa.Float(), nullable=True),
    sa.Column('atd_hours', sa.Float(), nullable=True),
    sa.Column('assigned_berth_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('inbound', 'anchored', 'berthed', 'working', 'departed', name='shipstatus'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('gate_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('en_route', 'queued', 'at_gate', 'in_yard', 'departed', name='truckstatus'), nullable=False),
    sa.Column('arrival_hours', sa.Float(), nullable=False),
    sa.Column('queue_wait_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yard_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('capacity_teu', sa.Integer(), nullable=False),
    sa.Column('occupied_teu', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yard_blocks')
    op.drop_table('trucks')
    op.drop_table('ships')
    op.drop_table('gates')
    op.drop_table('events')
    op.drop_table('cranes')
    op.drop_table('containers')
    op.drop_table('berths')
    op.drop_table('simulation_runs')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
